### PR TITLE
Fix omitempty typo in Node struct

### PR DESCRIPTION
**Pull request by dilipkk-foyernet**
only typo fix: omitemty -> omitempty

### CODE REVIEW

**Review by a8m — APPROVED** [review]

**Comment by dilipkk-foyernet** [comment]
@a8m I have run `go generate ./...` and committed but still, checks are failing. Can you plz look into it once?

**Comment by a8m** [comment]
Thanks for your contribution @dilipkk-foyernet 

Please run codegen and I’ll merge it.

**Comment by dilipkk-foyernet** [comment]
@a8m I am using ubuntu 20.04, and the ci server is using ubuntu 18.04, I suspect `entgql/internal/bindata.go` is not matching with what I am generating on my machine.

**Comment by dilipkk-foyernet** [comment]
@a8m I have executed the commands from ubuntu 18.04 and 20.04 and I see that no file is changed. Check the screenshot also
ent-contrib-2020-12-11_16-29

**Comment by a8m** [comment]
Both commands need to be executed from the `entgql` directory. Sorry for the confusion.

**Comment by dilipkk-foyernet** [comment]
I tried that also still no use.
ent-contrib-2020-12-11_16-30

**Comment by a8m** [comment]
OK, let me merge this with https://github.com/facebookincubator/ent-contrib/pull/21.

**Comment by a8m** [comment]
Done.

Code was landed in 99194204f8dbac16d45fddee9a6edd2d33510b48.

**Comment by dilipkk-foyernet** [comment]
Thanks a lot.

**Pull request closed without merging**
