### PR TITLE
examples: Add todo-uuids example that uses UUIDs for ids

### PR DESCRIPTION
**Pull request by tmc**
This adds a second example that uses UUIDs for the id column type.

This is currently failing with:
```
validation failed: packages.Load: facebookincubator/ent-contrib/entgql/internal/todo-uuids/generated.go:3127:17: ec.unmarshalInputID undefined (type *executionContext has no field or method unmarshalInputID)
facebookincubator/ent-contrib/entgql/internal/todo-uuids/generated.go:3132:12: ec._ID undefined (type *executionContext has no field or method _ID)
facebookincubator/ent-contrib/entgql/internal/todo-uuids/generated.go:3548:17: ec.unmarshalInputID undefined (type *executionContext has no field or method unmarshalInputID)
facebookincubator/ent-contrib/entgql/internal/todo-uuids/generated.go:3556:12: ec._ID undefined (type *executionContext has no field or method _ID)
facebookincubator/ent-contrib/entgql/internal/todo-uuids/todo.resolvers.go:21:23: cannot use todo.Parent (variable of type *uuid.UUID) as *int value in argument to client.Todo.Create().SetStatus(todo.Status).SetNillablePriority(todo.Priority).SetText(todo.Text).SetNillableParentID
facebookincubator/ent-contrib/entgql/internal/todo-uuids/todo.resolvers.go:33:29: cannot use id (variable of type uuid.UUID) as int value in argument to r.client.Noder
facebookincubator/ent-contrib/entgql/internal/todo-uuids/todo.resolvers.go:37:30: cannot use ids (variable of type []uuid.UUID) as []int value in argument to r.client.Noders
exit status 1
```

### CODE REVIEW

**Comment by a8m** [comment]
Thanks for reporting this issue @tmc, I'll try to address it later today. If you have time and want to fix it, go ahead and ping me if you need some help/guidance. Thanks 😃

**Comment by tmc** [comment]
> Thanks for reporting this issue @tmc, I'll try to address it later today. If you have time and want to fix it, go ahead and ping me if you need some help/guidance. Thanks 😃

I couldn't actually figure out what the cause was here, I was working on what's described in https://github.com/facebook/ent/issues/1099 and figured this was a smaller scope way to demonstrate some of the things I ran into.

**Comment by Sytten** [comment]
I am also using UUID as primary key and I get the following error when running gqlgen:
```
/Users/Sytten/Projects/***/Core2/pkg/ent/pagination.go:453:22: cannot use a.ID (variable of type uuid.UUID) as int value in struct literal
/Users/Sytten/Projects/***/Core2/pkg/ent/pagination.go:913:22: cannot use gf.ID (variable of type uuid.UUID) as int value in struct literal
/Users/Sytten/Projects/***/Core2/pkg/ent/pagination.go:1143:22: cannot use gt.ID (variable of type uuid.UUID) as int value in struct literal
/Users/Sytten/Projects/***/Core2/pkg/ent/pagination.go:1373:22: cannot use o.ID (variable of type uuid.UUID) as int value in struct literal
```

**Comment by a8m** [comment]
Some of the issues here are not related to ent/ent-contrib, like the missing [gql marshaller for google/uuid](https://github.com/google/uuid/pull/52). I created https://github.com/facebookincubator/ent-contrib/pull/32 that provides a working example, but I plan to improve it later. You're welcome to contribute changes to it. 

Closing.

**Comment by tmc** [comment]
Great to see this go in!

For the missing mashaler -- maybe ent could detect that situation and provide some guidance?

**Comment by Sytten** [comment]
The merged marshaler will cause typing issues with the google uuid because it is a custom uuid type. You can do something similar will using the google uuid by using s special name https://gqlgen.com/reference/scalars/#custom-scalars-with-third-party-types

Thats what I did and it works fine. The only problem is the pagination template that expects an int.

**Comment by a8m** [comment]
> The merged marshaler will cause typing issues with the google uuid because it is a custom uuid type. You can do something similar will using the google uuid by using s special name https://gqlgen.com/reference/scalars/#custom-scalars-with-third-party-types
> 
> Thats what I did and it works fine. The only problem is the pagination template that expects an int.

Thanks for the reference @Sytten.

**Pull request closed without merging**
