### PR TITLE
feat(edge): add Resolver annotation

### PR DESCRIPTION
**Pull request by giautm**
I added new annotation, but it have issue when trying to apply mutil-annotations with same type. So it delete code generate by `entgql.Bind()`. Look like this issue was fixed by https://github.com/facebook/ent/pull/927, but I don't know how to apply.

```diff
func (t *TodoQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *TodoQuery {
-	for _, field := range graphql.CollectFields(ctx, field.Selections, satisfies) {
-		switch field.Name {
-		case "children":
-			t = t.WithChildren(func(query *TodoQuery) {
-				query.collectField(ctx, field)
-			})
-		case "parent":
-			t = t.WithParent(func(query *TodoQuery) {
-				query.collectField(ctx, field)
-			})
-		}
-	}
	return t
}

```

### CODE REVIEW

**Comment by a8m** [comment]
Hey @giautm,
Can you please update ent version (for this module), and rerun codegen?

**Comment by giautm** [comment]
I tried, but it still have same issue. You can see the result at https://github.com/giautm/ent-contrib/commit/b171e9f21ce466140e0e638f49a07c4b5b0a26d6
```
vscode ➜ /workspaces/ent-contrib (devcontainer ✗) $ go mod tidy
vscode ➜ /workspaces/ent-contrib (devcontainer ✗) $ go get -u github.com/facebook/ent
vscode ➜ /workspaces/ent-contrib (devcontainer ✗) $ cd ./entgql/
vscode ➜ /workspaces/ent-contrib/entgql (devcontainer ✗) $ go generate ./...
go: finding module for package github.com/google/addlicense
go: found github.com/google/addlicense in github.com/google/addlicense v0.0.0-20200906110928-a0294312aa76
```

**Comment by a8m** [comment]
OK, let me giving it a deeper look.

**Comment by a8m** [comment]
I've checked it now, and it looks like the annotation merging logic works only for schema-level annotation (because the usage from mixin), so in this case, you should define the annotation as follows:

```go
Annotations(entgql.Annotation{
    Bind: true,
    Resolver: true,
})
```

I can improve the annotation part in ent later this week and then update this module. Thanks

**Comment by giautm** [comment]
Hi, I just update following your comments

**Comment by a8m** [comment]
Wonderful, thanks for your contribution @giautm 

Can you update ent documentation as well? It's [here](https://github.com/facebook/ent/blob/master/doc/md/graphql.md)

**Review by a8m — APPROVED** [review]

**Comment by a8m** [comment]
Hey @giautm,
Sorry for the inconvenience, but please see #23 

Thanks for your contribution, and I’ll update you once it’s done

**Pull request merged**
